Section A: Data Structures & Control Structures

1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [37]:
lis=[1,2,3,4,5]
print(lis)

[1, 2, 3, 4, 5]

In [38]:
#append
lis.append(10)
print(lis)

[1, 2, 3, 4, 5, 10]

In [39]:
#extend
lis1=[9,7,6]
lis.extend(lis1)
print(lis)

[1, 2, 3, 4, 5, 10, 9, 7, 6]

In [40]:
#insert
lis.insert(4,66)
print(lis)

[1, 2, 3, 4, 66, 5, 10, 9, 7, 6]

In [41]:
#remove
lis.remove(6)
print(lis)

[1, 2, 3, 4, 66, 5, 10, 9, 7]

In [ ]:
#pop
lis.pop(1)
print(lis)

2

In [48]:
#clear
temp=lis.copy() #copied the list to a variable named temp
print(temp)
temp.clear()
print(temp)

[66, 10, 9, 7, 5, 4, 3, 1]
[]

In [47]:
#count
c=lis.count(66)
print(c)

1

In [44]:
#sort
lis.sort()
print(lis)

[1, 3, 4, 5, 7, 9, 10, 66]

In [45]:
#reverse
lis.reverse()
print(lis)

[66, 10, 9, 7, 5, 4, 3, 1]

2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [67]:
#creating a tuple with 3 student names
tup=('Ethen','Caleb','Ava') 
print(tup)

('Ethen', 'Caleb', 'Ava')

In [68]:
try:
    tup[1]='Ezra'
except TypeError as e:
    print("Error:",e)
    print('tuple is immutable, so we cannot change the values of tuple')

Error: 'tuple' object does not support item assignment
tuple is immutable, so we cannot change the values of tuple

3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [77]:
se={1,2,1,3,1,4,1,5}
print(se)
print('Set does not allow duplicate values.\nTherefore, duplicate values such as 1, 2, and 3 are automatically removed, and each value appears only once.')

{1, 2, 3, 4, 5}
Set does not allow duplicate values.
Therefore, duplicate values such as 1, 2, and 3 are automatically removed, and each value appears only once.

4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [79]:
di={'name':'abc','age':21,'city':'NeyYork'} #a dictionary with keys and values is created
print(di)

{'name': 'abc', 'age': 21, 'city': 'NeyYork'}

In [80]:
#updating age
di['age']=22
print(di)

{'name': 'abc', 'age': 22, 'city': 'NeyYork'}

In [81]:
#adding new key
di['email']='abc@gmail.com'
print(di)

{'name': 'abc', 'age': 22, 'city': 'NeyYork', 'email': 'abc@gmail.com'}

5.	 Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [86]:
age=int(input())
if age<18:
    print('Not eligible to vote')
else:
    print('Eligible to vote')

Eligible to vote

6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'

In [92]:
marks=96
print('A' if marks>=90 else 'B' if marks>=75 and marks<=89 else 'C' if marks>=50 and marks<=74 else 'Fail')

A

7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [107]:
num=10
if num>0:
    if num%2==0:
        print(f"{num} is positive and also even")
    else:
        print(f"{num} is positive but not even")
elif num==0:
    print(f"{num} is zero")
else:
    print(f"{num} is negative")

10 is positive and also even

Section B: Numpy

8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10

In [108]:
import numpy as np

In [110]:
#A scalar using np.array(5)
scaler=np.array(5)
print(scaler)

5

In [112]:
#A 1D array with values 1 to 5
one_d_array=np.arange(1,6)
print(one_d_array)

[1 2 3 4 5]

In [117]:
#A 2D array (2x3) with values from 10 to 60 in steps of 10
two_d_array=np.arange(10,70,10).reshape(2,3)
print(two_d_array)

[[10 20 30]
 [40 50 60]]

9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [128]:
a=np.random.randint(0,100,size=(4,4))
print(a)

[[53 41 27 85]
 [26  3 14 82]
 [16 45 49 96]
 [41 83 81 93]]

10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [131]:
import pandas as pd

In [ ]:
#creating a 3 x 3 numpy array
b=np.random.randint(30,size=(3,3))
print("Numpy array:")
print(b)
print("\n pandas DataFrame:")
c=pd.DataFrame(b,columns=['A','B','C'])
c

Numpy array:
[[25  6  7]
 [16  9  5]
 [ 8 12 21]]

pandas DataFrame:

    A   B   C
0  25   6   7
1  16   9   5
2   8  12  21

Section C: Exploring Pandas

11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows

In [ ]:
# Creating dataframe with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'
data = {
    'Name': ['Tony Stark', 'Bruce Wayne', 'Peter Parker', 'Clark Kent', 'Diana Prince', 
             'Barry Allen', 'Natasha Romanoff', 'Steve Rogers', 'Matt Murdock', 'Peter Parker'],
    'Age': [45, 38, 21, 33, 800, 28, 34, 105, 30, 21],
    'City': ['New York', 'Gotham', 'Queens', 'Metropolis', 'Washington D.C.', 
             'Central City', 'Moscow', 'Brooklyn', "Hell's Kitchen", 'Queens'],
    'Salary': [5000000, 5000000, 35000, np.nan, 95000, 72000, 120000, np.nan, 55000, 35000]
}

In [176]:
#Converting to DataFrame
df = pd.DataFrame(data)

In [177]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     str
 1   Age     10 non-null     int64
 2   City    10 non-null     str
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), str(2)
memory usage: 452.0 bytes

In [178]:
df.describe()

              Age        Salary
count   10.000000  8.000000e+00
mean   115.500000  1.301500e+06
std    241.730451  2.282945e+06
min     21.000000  3.500000e+04
25%     28.500000  5.000000e+04
50%     33.500000  8.350000e+04
75%     43.250000  1.340000e+06
max    800.000000  5.000000e+06

In [179]:
#Select 'Name' and 'City' columns
df[['Name','City']]

               Name             City
0        Tony Stark         New York
1       Bruce Wayne           Gotham
2      Peter Parker           Queens
3        Clark Kent       Metropolis
4      Diana Prince  Washington D.C.
5       Barry Allen     Central City
6  Natasha Romanoff           Moscow
7      Steve Rogers         Brooklyn
8      Matt Murdock   Hell's Kitchen
9      Peter Parker           Queens

In [180]:
#Drop 'City' column
df.drop(columns=['City'],inplace=True)
df

               Name  Age     Salary
0        Tony Stark   45  5000000.0
1       Bruce Wayne   38  5000000.0
2      Peter Parker   21    35000.0
3        Clark Kent   33        NaN
4      Diana Prince  800    95000.0
5       Barry Allen   28    72000.0
6  Natasha Romanoff   34   120000.0
7      Steve Rogers  105        NaN
8      Matt Murdock   30    55000.0
9      Peter Parker   21    35000.0

In [181]:
#Fill any missing values in 'Salary' column with the mean
df.isnull().sum()

Name      0
Age       0
Salary    2
dtype: int64

In [186]:
df['Salary']=df['Salary'].fillna(df['Salary'].mean())

In [187]:
df

               Name  Age     Salary
0        Tony Stark   45  5000000.0
1       Bruce Wayne   38  5000000.0
2      Peter Parker   21    35000.0
3        Clark Kent   33  1301500.0
4      Diana Prince  800    95000.0
5       Barry Allen   28    72000.0
6  Natasha Romanoff   34   120000.0
7      Steve Rogers  105  1301500.0
8      Matt Murdock   30    55000.0
9      Peter Parker   21    35000.0

In [188]:
#Remove any duplicate rows
df.duplicated().sum()

np.int64(1)

In [191]:
df.drop_duplicates(inplace=True)

In [192]:
df

               Name  Age     Salary
0        Tony Stark   45  5000000.0
1       Bruce Wayne   38  5000000.0
2      Peter Parker   21    35000.0
3        Clark Kent   33  1301500.0
4      Diana Prince  800    95000.0
5       Barry Allen   28    72000.0
6  Natasha Romanoff   34   120000.0
7      Steve Rogers  105  1301500.0
8      Matt Murdock   30    55000.0