BASIC STATISTICS-2

Problem Statement : Hospital Patient Data Analysis

Context:

A hospital maintains patient records including admission details, department, diagnosis, doctor, and bill amount. You have two datasets: one with patient info and another with billing details. Some patients have blank bill amounts, and there are multiple rows for the same patient due to follow-ups.

In [1]:
import pandas as pd
import numpy as np

1.	Load the patient dataset and show summary with info().

In [2]:
df=pd.read_csv('Patient_Data.csv')

In [3]:
df2=pd.read_csv('Billing_Data.csv')

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      str
 2   Department      6 non-null      str
 3   Doctor          6 non-null      str
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      str
dtypes: float64(1), int64(2), str(4)
memory usage: 703.0 bytes

In [5]:
df

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45
5,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00

2.	Select only the columns relevant for billing: ['PatientID', 'Department', 'Doctor', 'BillAmount'].

In [6]:
billing_columns=df[['PatientID', 'Department', 'Doctor', 'BillAmount']]

print(billing_columns.columns)

Index(['PatientID', 'Department', 'Doctor', 'BillAmount'], dtype='str')

3.	Drop administrative columns like ['ReceptionistID', 'CheckInTime'].

In [7]:
df=df.drop(columns=['ReceptionistID', 'CheckInTime'])
df

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN
5        101    Alice   Cardiology  Dr. Smith      5000.0

4.	Use groupby to find total bill amount per department.

In [8]:
total_bill_per_departmnt=df.groupby('Department')['BillAmount'].sum()

print(total_bill_per_departmnt)

Department
Cardiology     16200.0
Dermatology        0.0
Neurology          0.0
Orthopedics     7500.0
Name: BillAmount, dtype: float64

5.	Remove duplicate patient records based on PatientID.

In [9]:
df.duplicated().sum()

np.int64(1)

In [10]:
df.drop_duplicates(inplace=True)

In [11]:
df.duplicated().sum() #duplicates are removed

np.int64(0)

6.	Fill missing BillAmount values with the mean bill amount.

In [12]:
df['BillAmount']=df['BillAmount'].fillna(df['BillAmount'].mean())

In [13]:
df

   PatientID     Name   Department     Doctor   BillAmount
0        101    Alice   Cardiology  Dr. Smith  5000.000000
1        102      Bob    Neurology   Dr. John  6233.333333
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000
3        104    David   Cardiology  Dr. Smith  6200.000000
4        105      Eva  Dermatology   Dr. Rose  6233.333333

7.	Merge the billing dataset with patient dataset on PatientID.

In [14]:
merged_df=pd.merge(df,df2,on='PatientID')
merged_df

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000

8.	Concatenate an additional DataFrame that contains new patients for the current week (row-wise).

In [15]:
new_patients=pd.DataFrame({
    'PatientID':[106, 107],
    'Name':['Frank', 'Grace'],
    'Department':['Cardiology', 'Neurology'],
    'Doctor':['Dr. Strange', 'Dr. Banner'],
    'BillAmount':[6500, 4800]
})

In [16]:
new_patients

   PatientID   Name  Department       Doctor  BillAmount
0        106  Frank  Cardiology  Dr. Strange        6500
1        107  Grace   Neurology   Dr. Banner        4800

In [17]:
df=pd.concat([df,new_patients],ignore_index=True)
df

   PatientID     Name   Department       Doctor   BillAmount
0        101    Alice   Cardiology    Dr. Smith  5000.000000
1        102      Bob    Neurology     Dr. John  6233.333333
2        103  Charlie  Orthopedics      Dr. Lee  7500.000000
3        104    David   Cardiology    Dr. Smith  6200.000000
4        105      Eva  Dermatology     Dr. Rose  6233.333333
5        106    Frank   Cardiology  Dr. Strange  6500.000000
6        107    Grace    Neurology   Dr. Banner  4800.000000

9.	Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise).

In [18]:
new_col=pd.DataFrame({
    'InsuranceCovered':[1000,2000,1500,1200,1800,1600,1900],
    'FinalAmount':[4000,4233.33,6000,5000,4433.33,3000,54.44]
})

In [19]:
df=pd.concat([df,new_col],axis=1)
df

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,1000,4000.00
1,102,Bob,Neurology,Dr. John,6233.333333,2000,4233.33
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,1500,6000.00
3,104,David,Cardiology,Dr. Smith,6200.000000,1200,5000.00
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1800,4433.33
5,106,Frank,Cardiology,Dr. Strange,6500.000000,1600,3000.00
6,107,Grace,Neurology,Dr. Banner,4800.000000,1900,54.44